SET client_encoding = 'UTF8';

CREATE TABLE location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    x INTEGER NOT NULL,
    y BIGINT NOT NULL,
    z REAL NOT NULL
);

CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    eye_color VARCHAR(20),
    hair_color VARCHAR(20) NOT NULL,
    location_id BIGINT REFERENCES location (id),
    weight BIGINT,
    nationality VARCHAR(20),
    CONSTRAINT person_name_nonempty CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT person_eye_color_known CHECK (eye_color IS NULL OR eye_color IN ('RED', 'BLACK', 'YELLOW', 'BROWN')),
    CONSTRAINT person_hair_color_known CHECK (hair_color IN ('RED', 'BLACK', 'YELLOW', 'BROWN')),
    CONSTRAINT person_weight_positive CHECK (weight IS NULL OR weight > 0),
    CONSTRAINT person_nationality_known CHECK (nationality IS NULL OR nationality IN ('RUSSIA', 'GERMANY', 'SPAIN', 'INDIA'))
);

CREATE TABLE coordinates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    x BIGINT NOT NULL,
    y REAL NOT NULL,
    CONSTRAINT coordinates_x_max CHECK (x <= 139)
);

CREATE TABLE discipline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    lecture_hours INTEGER NOT NULL,
    self_study_hours BIGINT NOT NULL,
    labs_count INTEGER NOT NULL,
    CONSTRAINT discipline_name_nonempty CHECK (char_length(btrim(name)) > 0)
);

CREATE TABLE lab_work (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    coordinates_id BIGINT NOT NULL REFERENCES coordinates (id),
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR(2960),
    difficulty VARCHAR(20),
    discipline_id BIGINT NOT NULL REFERENCES discipline (id),
    minimal_point BIGINT NOT NULL,
    tuned_in_works INTEGER,
    author_id BIGINT REFERENCES person (id),
    CONSTRAINT lab_work_id_positive CHECK (id > 0),
    CONSTRAINT lab_work_name_nonempty CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT lab_work_description_len CHECK (description IS NULL OR char_length(description) <= 2960),
    CONSTRAINT lab_work_difficulty_known CHECK (
        difficulty IS NULL OR difficulty IN ('NORMAL', 'HARD', 'VERY_HARD', 'IMPOSSIBLE', 'TERRIBLE')
    ),
    CONSTRAINT lab_work_minimal_point_positive CHECK (minimal_point > 0)
);

CREATE TABLE discipline_program (
    discipline_id BIGINT NOT NULL REFERENCES discipline (id),
    lab_work_id INTEGER NOT NULL REFERENCES lab_work (id),
    PRIMARY KEY (discipline_id, lab_work_id)
);

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(16) NOT NULL,
    CONSTRAINT app_user_username_nonempty CHECK (char_length(btrim(username)) > 0),
    CONSTRAINT app_user_role_known CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE user_session (
    token VARCHAR(36) PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_person_location ON person (location_id);
CREATE INDEX idx_lab_work_coordinates ON lab_work (coordinates_id);
CREATE INDEX idx_lab_work_discipline ON lab_work (discipline_id);
CREATE INDEX idx_lab_work_author ON lab_work (author_id);
CREATE INDEX idx_program_lab ON discipline_program (lab_work_id);

CREATE OR REPLACE FUNCTION avg_minimal_point()
RETURNS DOUBLE PRECISION
LANGUAGE sql
STABLE
AS $$
    SELECT AVG(minimal_point)::double precision FROM lab_work;
$$;

CREATE OR REPLACE FUNCTION lab_works_by_description(p_substring TEXT)
RETURNS SETOF lab_work
LANGUAGE sql
STABLE
AS $$
    SELECT lw.*
    FROM lab_work lw
    WHERE p_substring IS NOT NULL
      AND char_length(p_substring) > 0
      AND lw.description IS NOT NULL
      AND strpos(lw.description, p_substring) > 0
    ORDER BY lw.id;
$$;

CREATE OR REPLACE FUNCTION unique_minimal_points()
RETURNS TABLE(point_value BIGINT)
LANGUAGE sql
STABLE
AS $$
    SELECT DISTINCT lw.minimal_point AS point_value
    FROM lab_work lw
    ORDER BY point_value;
$$;

CREATE OR REPLACE FUNCTION decrease_labwork_difficulty(p_id INTEGER, p_steps INTEGER)
RETURNS VARCHAR
LANGUAGE plpgsql
AS $$
DECLARE
    v_current VARCHAR(20);
    v_ranks TEXT[] := ARRAY['NORMAL', 'HARD', 'VERY_HARD', 'IMPOSSIBLE', 'TERRIBLE'];
    v_index INTEGER;
    v_next INTEGER;
BEGIN
    IF p_id IS NULL THEN
        RAISE EXCEPTION 'Не указана лабораторная работа';
    END IF;
    IF p_steps IS NULL OR p_steps <= 0 THEN
        RAISE EXCEPTION 'Число шагов должно быть больше 0';
    END IF;

    SELECT difficulty INTO v_current
    FROM lab_work
    WHERE id = p_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Лабораторная работа с id % не найдена', p_id;
    END IF;
    IF v_current IS NULL THEN
        RAISE EXCEPTION 'У лабораторной работы не задана сложность, понижать нечего';
    END IF;

    v_index := array_position(v_ranks, v_current);
    IF v_index IS NULL THEN
        RAISE EXCEPTION 'Неизвестная сложность: %', v_current;
    END IF;

    v_next := v_index - p_steps;
    IF v_next < 1 THEN
        RAISE EXCEPTION 'Нельзя понизить сложность на % (сейчас %, минимум — NORMAL)', p_steps, v_current;
    END IF;

    UPDATE lab_work
    SET difficulty = v_ranks[v_next]
    WHERE id = p_id;

    RETURN v_ranks[v_next];
END;
$$;

CREATE OR REPLACE FUNCTION add_hardest_labworks(p_discipline_id BIGINT)
RETURNS TABLE(work_id INTEGER, inserted_now BOOLEAN)
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_discipline_id IS NULL OR NOT EXISTS (SELECT 1 FROM discipline d WHERE d.id = p_discipline_id) THEN
        RAISE EXCEPTION 'Дисциплина не найдена';
    END IF;

    RETURN QUERY
    WITH hardest AS (
        SELECT lw.id
        FROM lab_work lw
        WHERE lw.difficulty IS NOT NULL
        ORDER BY CASE lw.difficulty
                     WHEN 'TERRIBLE' THEN 5
                     WHEN 'IMPOSSIBLE' THEN 4
                     WHEN 'VERY_HARD' THEN 3
                     WHEN 'HARD' THEN 2
                     WHEN 'NORMAL' THEN 1
                     ELSE 0
                 END DESC,
                 lw.minimal_point DESC,
                 lw.id ASC
        LIMIT 10
    ),
    inserted AS (
        INSERT INTO discipline_program (discipline_id, lab_work_id)
        SELECT p_discipline_id, h.id
        FROM hardest h
        ON CONFLICT DO NOTHING
        RETURNING discipline_program.lab_work_id
    )
    SELECT h.id, (i.lab_work_id IS NOT NULL)
    FROM hardest h
    LEFT JOIN inserted i ON i.lab_work_id = h.id
    ORDER BY h.id;
END;
$$;
